Introduce MarkdownText to render markdown strings
halilozercan/compose-richtext pull request #1
Opened 2020-10-13 18:51 UTC by halilozercan

- Convert `RichTextScope` "Object -> Interface" to support extension scopes such as `MarkdownTextScope`
- Add commonmark dependencies for Markdown AST parsing.
- Add `Markdown Demo`
- TableStyle now supports custom header background color. However, this doesn't work well for DarkMode with the current API.

2020-10-23 17:11 UTC, zach-klippenstein requested changes
This is really cool, thanks for doing this! I did a first-pass review, I might have missed some stuff but left a bunch of comments already. Also, would love if you targeted this PR to the main repo, so it doesn't just live in your fork, if you're open to that.

The CommonMark dependencies and integration should be in a separate module (e.g. `richtext-commonmark`). That way users of `richtext-ui` don't need to pull in the entire commonmark library if they don't want it.

2020-10-23 17:11 UTC, zach-klippenstein commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/TraverseUtils.kt
> +    Log.d("Visit", "--".repeat(depth) + " ${node::class.simpleName}")
Did you mean to leave this in?

2020-10-23 17:11 UTC, zach-klippenstein commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/ASTTable.kt
> +    object  ASTTableBody: ASTTable()
What is this? A cell type? Please add kdoc.

2020-10-23 17:11 UTC, zach-klippenstein commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/ASTTable.kt
> +    data class ASTTableCell(
The above all look like cells, so how does this type relate to the others? Please add kdoc.

2020-10-23 17:11 UTC, zach-klippenstein commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/ASTNode.kt
> +fun convert(
Should this function be internal?

2020-10-23 17:11 UTC, zach-klippenstein commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/ASTNode.kt
> +        get() = delimiter
Just make `delimiter` public and reference it directly. These properties can be added later if they're actually needed.

2020-10-23 17:23 UTC, halilozercan commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-rc-4-all.zip
Canary 14 required AGP to be alpha14, that required gradle to be an RC version :/

2020-10-23 18:13 UTC, halilozercan commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/Table.kt
> +      .clipToBounds()
I believe it was already clipped, my addition was to add a `fillMaxWidth` to make even tables.

2020-10-23 18:22 UTC, halilozercan commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/ASTTable.kt
> +sealed class ASTTable {
How about 
```
@Immutable
sealed class AstTableSection {

    @Immutable
    object Root: AstTableSection()

    @Immutable
    object Body: AstTableSection()

    @Immutable
    object Header: AstTableSection()

    @Immutable
    object Row: AstTableSection()

    @Immutable
    data class Cell(
        val header: Boolean,
        val alignment: AstTableCellAlignment
    ): AstTableSection()
}
```

2020-10-23 18:28 UTC, halilozercan commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/BlockRender.kt
> +    Text(text = richTextString {
It's an artifact from earlier implementation. Going to remove.

2020-10-23 18:35 UTC, halilozercan commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/Markdown.kt
> +        }
can't quite understand what you mean by this line

```val onLinkClicked by rememberUpdatedState(onLinkClicked)```

2020-10-23 18:37 UTC, halilozercan commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/Markdown.kt
> +
The suggested change below (LaunchedTask) actually renders this coroutineScope useless. I'm going to skip this one.

2020-10-23 18:37 UTC, halilozercan commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/Markdown.kt
> +
Saw a bit late :) 

```And then you can delete the explicit scope altogether.```

2020-10-23 18:41 UTC, halilozercan commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/Markdown.kt
> +    }
I revised `filterChildren` function to return a sequence. Added another function called `childrenSequence`

```
internal fun AstNode.childrenSequence(): Sequence<AstNode> {
    return this.filterChildren { true }
}
```

2020-10-23 18:42 UTC, halilozercan commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/MarkdownRichText.kt
> + * as a child to include any further RichText.
CommonMark invariant.

2020-10-23 18:59 UTC, halilozercan commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/ASTNode.kt
> +fun convert(
Yes this is where we transfer from commonmark to our own nodes. `AST` prefix turned into an eyesore for me as well but I just went with `Ast`. Prefix doesn't really feel comfortable to me as well but as you said clash between composables, commonmark's node names, and these nodes would be quite a mess. 

As you said, separate module would be the cleanest solution.

2020-10-23 18:59 UTC, halilozercan commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/Markdown.kt
> +fun Markdown(
Great idea. Will look into that later.

2020-10-23 18:59 UTC, halilozercan commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/TraverseUtils.kt
> +    Log.d("Visit", "--".repeat(depth) + " ${node::class.simpleName}")
not at all :)

2020-10-23 19:05 UTC, halilozercan commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/markdown/ASTNode.kt
> +    override fun equals(other: Any?): Boolean {
again an artifact from experiments. Should have never been in the PR :/

2020-10-25 19:27 UTC, zach-klippenstein commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-rc-4-all.zip
That's odd, I've been using it without a Gradle rc just fine.

2020-10-25 19:28 UTC, zach-klippenstein commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-rc-4-all.zip
At any rate, this should be done separately, and 6.7 is released now (I think the main branch should have it, if you rebase).

2020-10-26 10:42 UTC, halilozercan commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-rc-4-all.zip
Couldn't find it on main branch but bumped it to 6.7 anyway.

2020-10-26 16:52 UTC, zach-klippenstein commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-rc-4-all.zip
Hm, the main repo's main branch is definitely using 6.7. Are you sure you fetched from the right repo?

2020-10-26 16:54 UTC, zach-klippenstein commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/Table.kt
> +      .clipToBounds()
Derp, you're right. Filed: https://github.com/zach-klippenstein/compose-richtext/issues/10

2020-10-26 16:57 UTC, zach-klippenstein commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/Table.kt
> +      .clipToBounds()
This change seems unrelated to markdown support though. Probably we need a new API for this. Maybe the theme should allow you to specify providers for modifiers for table cells? This could also be used to implement stuff like zebra striping.

2020-10-26 17:54 UTC, halilozercan commented on richtext-ui/src/main/java/com/zachklipp/richtext/ui/Table.kt
> +      .clipToBounds()
Ok, gonna leave this out

2020-10-26 17:59 UTC, halilozercan commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-rc-4-all.zip
https://github.com/zach-klippenstein/compose-richtext/blob/main/gradle/wrapper/gradle-wrapper.properties#L3

Isn't this where I should be looking at?

2020-10-27 16:30 UTC, zach-klippenstein commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-rc-4-all.zip
Wow, yes, I was definitely looking at the wrong repo. I need to stop prefixing things with `compose-` 🤦  You are right. Fixed now: https://github.com/zach-klippenstein/compose-richtext/pull/13

2020-10-28 00:15 UTC, zach-klippenstein requested changes
Just a few more things.

2020-10-28 00:15 UTC, zach-klippenstein commented on markdown/src/main/java/com/zachklipp/richtext/markdown/extensions/AstStrikethrough.kt
> +data class AstStrikethrough(
Can this be internal?

2020-10-28 00:15 UTC, zach-klippenstein commented on markdown/src/main/java/com/zachklipp/richtext/markdown/extensions/AstTable.kt
> +data class AstTableRoot(
Can all these be internal as well?

2020-10-28 00:15 UTC, zach-klippenstein commented on settings.gradle
> +include ':markdown'
I think this module should be called `richtext-commonmark`, since it directly integrates with the `richtext-ui` module, and it's specifically dependent on CommonMark.

2020-10-28 00:16 UTC, zach-klippenstein commented on markdown/src/main/java/com/zachklipp/richtext/markdown/AstNode.kt
> +interface AstNode {
Internal here too?

2020-10-28 13:25 UTC, zach-klippenstein approved these changes

2020-10-28 13:25 UTC, zach-klippenstein commented on richtext-commonmark/src/main/java/com/zachklipp/richtext/markdown/Markdown.kt
> +        Providers(AmbientOnLinkClicked provides (onLinkClicked ?: {})) {
This could be addressed in a follow up, but I wonder if it would be reasonable to default to the current UriHandler ambient for links instead of no-oping.

2020-10-28 13:25 UTC, zach-klippenstein commented on richtext-commonmark/src/main/java/com/zachklipp/richtext/markdown/Markdown.kt
> +    LaunchedTask(text) {
Nit: Don't know why I didn't think of this sooner, but this remember + LaunchedTask could be condensed into a [produceState](https://developer.android.com/reference/kotlin/androidx/compose/runtime/package-summary#producestate). No need to block the merge on this though.

2020-10-28 13:25 UTC, zach-klippenstein commented on richtext-commonmark/src/main/java/com/zachklipp/richtext/markdown/Markdown.kt
> +internal fun parsedMarkdownAst(text: String): AstNode? {
Nit: this function should come before RecursiveRender since it is called first.

2020-10-28 13:25 UTC, zach-klippenstein commented on richtext-commonmark/src/main/java/com/zachklipp/richtext/markdown/Markdown.kt
> +        Providers(AmbientOnLinkClicked provides (onLinkClicked ?: {})) {
Nit: This could be done in a follow-up, but I wonder if using the current UriHandler ambient for the default would be more reasonable than no-oping.

2020-10-28 13:35 UTC, halilozercan commented on richtext-commonmark/src/main/java/com/zachklipp/richtext/markdown/Markdown.kt
> +        Providers(AmbientOnLinkClicked provides (onLinkClicked ?: {})) {
Wow, I wasn't even aware of that Ambient. We can squeeze that into this PR before merging.

2020-10-28 14:00 UTC, merged

2020-10-28 15:47 UTC, zach-klippenstein commented on richtext-commonmark/src/main/java/com/zachklipp/richtext/markdown/Markdown.kt
> +        Providers(AmbientOnLinkClicked provides (onLinkClicked ?: {})) {
It seems like a weird hacky/shortcut solution to a very specific problem, and AFAIK there's nothing like it in stock android, but it's there we might as well use it ¯\_(ツ)_/¯